"""Durable, dependency-free storage for raw collection episodes.

The raw recorder is intentionally small and boring.  It writes length-prefixed
JSON records with a CRC32 to bounded chunk files, keeps encoded camera payloads
unchanged, and uses one manifest as the lifecycle authority.  MP4/Parquet are
derived artifacts and never participate in the recording hot path.
"""

from __future__ import annotations

import base64
import binascii
import copy
import hashlib
import json
import math
import os
import re
import struct
import threading
import time
import uuid
from collections.abc import Iterator, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any


SCHEMA = "robo_collector.raw_episode.v1"
SOURCE_SCOPES = {"transport_observed", "camera_capture"}
STATUSES = {
    "OPEN",
    "RAW_CLOSED",
    "MATERIALIZING",
    "MATERIALIZATION_FAILED",
    "MATERIALIZED",
    "QC",
    "READY",
    "REVIEW",
    "REJECT",
    "DISCARDED",
    "QUARANTINED",
}
JOB_STATUSES = {"PENDING", "RUNNING", "MATERIALIZED", "FAILED", "DISCARDED"}

_SAFE_COMPONENT = re.compile(r"^[A-Za-z0-9_.-]+$")
_SESSION_ID = re.compile(r"^[A-Za-z0-9_.:-]+$")
_HEADER = struct.Struct(">4sQI")
_MAGIC = b"RER1"
_DEFAULT_MAX_RECORD_BYTES = 16 * 1024 * 1024
_DEFAULT_MAX_RECORDS_PER_CHUNK = 1000
_RESERVED_EXTRA_FIELDS = frozenset(
    {
        "episode_id",
        "stream_name",
        "session_id",
        "sequence",
        "clock_domain",
        "device_timestamp",
        "device_unit",
        "server_wall_timestamp",
        "server_monotonic_timestamp",
        "receive_wall_timestamp",
        "receive_monotonic_timestamp",
        "record_monotonic_timestamp",
        "payload",
        "payload_encoding",
        "payload_size_bytes",
        "state",
        # Alignment/provenance fields are materialization outputs.  They must
        # be generated by the materializer rather than supplied as capture
        # metadata that could be mistaken for source evidence.
        "selected_dataset_timestamp",
        "alignment_residual_sec",
        "alignment_target_source_timestamp",
        "target_timestamp_sec",
        "selection_policy",
        "alignment_selection_policy",
        "action_policy",
        "state_residual_sec",
        "camera_residuals_sec",
        "state_sequence",
        "camera_sequences",
        "action_sequence",
    }
)


class RawEpisodeError(RuntimeError):
    """Base error for raw episode and job state failures."""


class CorruptChunk(RawEpisodeError):
    """Raised when a raw chunk has a truncated or invalid record."""


@dataclass
class _ChunkHandle:
    handle: Any
    index: int
    record_count: int

    def __getitem__(self, index: int) -> Any:
        """Keep the old private tuple shape usable by recovery tests."""
        return (self.handle, self.index, self.record_count)[index]


def _json_bytes(value: Any) -> bytes:
    try:
        return json.dumps(
            value,
            sort_keys=True,
            ensure_ascii=False,
            separators=(",", ":"),
            allow_nan=False,
        ).encode("utf-8")
    except (TypeError, ValueError) as exc:
        raise ValueError(f"raw record is not JSON serializable: {exc}") from exc


def _canonical_value(value: Any) -> Any:
    """Return JSON data normalized through the same safe encoder used on disk."""
    return json.loads(_json_bytes(value).decode("utf-8"))


def _safe_output_target(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, (str, os.PathLike)):
        target = Path(value)
        if target.is_absolute() or ".." in target.parts:
            raise ValueError("output_target must not escape its configured root")
        return str(target)
    return _canonical_value(value)


def _sync_file(handle: Any) -> None:
    handle.flush()
    os.fsync(handle.fileno())


def _sync_dir(path: Path) -> None:
    try:
        fd = os.open(path, os.O_RDONLY)
    except OSError:
        return
    try:
        os.fsync(fd)
    except OSError:
        pass
    finally:
        os.close(fd)


def _atomic_json(path: Path, value: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.{uuid.uuid4().hex}.tmp")
    data = _json_bytes(value)
    try:
        with temporary.open("wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
        _sync_dir(path.parent)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def _publish_manifest(path: Path, manifest: Mapping[str, Any]) -> None:
    """Durably publish the progress manifest as the final manifest."""
    progress = path / "manifest.inprogress.json"
    final = path / "manifest.json"
    _atomic_json(progress, manifest)
    # _atomic_json fsyncs the file before this rename.  Keeping this as a
    # progress -> final rename makes a crash leave at least one valid copy.
    os.replace(progress, final)
    _sync_dir(path)


def _safe_component(value: str, field: str) -> str:
    if not isinstance(value, str) or not value or not _SAFE_COMPONENT.fullmatch(value):
        raise ValueError(f"unsafe {field}: {value!r}")
    return value


def _safe_episode_id(value: str) -> str:
    if not isinstance(value, str) or not value or not _SESSION_ID.fullmatch(value):
        raise ValueError(f"unsafe episode_id: {value!r}")
    return value


def _finite_number(value: Any, field: str) -> float:
    if isinstance(value, bool):
        raise ValueError(f"{field} must be finite")
    try:
        number = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{field} must be finite") from exc
    if not math.isfinite(number):
        raise ValueError(f"{field} must be finite")
    return number


def _sequence(value: Any, field: str = "sequence") -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        raise ValueError(f"{field} must be a non-negative integer")
    return value


def _hash_manifest(manifest: Mapping[str, Any]) -> str:
    payload = dict(manifest)
    payload.pop("manifest_hash", None)
    payload.pop("raw_manifest_hash", None)
    # Job/QC state is mutable after the raw close.  The source hash must stay
    # stable so retries remain idempotent and derived artifacts can point back
    # to the same immutable capture.
    payload.pop("status", None)
    payload.pop("materialization_jobs", None)
    payload.pop("artifacts", None)
    payload.pop("quality", None)
    # Discard/quarantine are mutable lifecycle decisions made after the raw
    # capture is sealed.  They must not invalidate the immutable source hash;
    # otherwise a deliberately discarded episode is quarantined on restart.
    payload.pop("discarded_at", None)
    payload.pop("discard_reason", None)
    payload.pop("quarantine_error", None)
    return hashlib.sha256(_json_bytes(payload)).hexdigest()


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _raw_files(path: Path) -> list[Path]:
    return sorted(path.rglob("*.raw"))


def _checksums(path: Path) -> dict[str, str]:
    return {str(file.relative_to(path)): _sha256(file) for file in _raw_files(path)}


def _write_checksums(path: Path, checksums: Mapping[str, str]) -> None:
    _atomic_json(
        path / "checksums.json",
        {
            "schema": f"{SCHEMA}.checksums.v1",
            "files": dict(checksums),
        },
    )


def _read_checksums(path: Path) -> dict[str, str]:
    checksum_path = path / "checksums.json"
    if not checksum_path.exists():
        return {}
    try:
        value = json.loads(checksum_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise CorruptChunk(f"cannot read checksums: {checksum_path}") from exc
    if not isinstance(value, Mapping):
        raise CorruptChunk("checksums.json must be an object")
    files = value.get("files", value)
    if not isinstance(files, Mapping):
        raise CorruptChunk("checksums.json files must be an object")
    return {str(name): str(checksum) for name, checksum in files.items()}


def _manifest_path(path: Path) -> Path:
    closed = path / "manifest.json"
    progress = path / "manifest.inprogress.json"
    if closed.exists():
        return closed
    if progress.exists():
        return progress
    raise RawEpisodeError(f"raw episode manifest is missing: {path}")


def _read_manifest(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(_manifest_path(path).read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise RawEpisodeError(f"cannot read raw episode manifest: {path}") from exc
    if not isinstance(value, dict):
        raise RawEpisodeError(f"raw episode manifest must be an object: {path}")
    return value


def _ensure_startup_quality_report(
    path: Path,
    manifest: Mapping[str, Any],
) -> None:
    """Ensure every recoverable sealed episode has a durable QC report."""
    target = path / "quality.json"
    if target.is_file() and target.stat().st_size > 0:
        try:
            value = json.loads(target.read_text(encoding="utf-8"))
            if (
                isinstance(value, Mapping)
                and value.get("report_schema") == "robo_collector.episode_quality.v1"
                and value.get("status")
                in {"READY", "REVIEW", "REJECT", "DISCARDED", "QUARANTINED"}
            ):
                return
        except (OSError, UnicodeDecodeError, json.JSONDecodeError):
            pass

    # Import lazily: episode_quality validates raw episodes through this
    # module, so importing it at module load time would create a cycle.
    from .episode_quality import EpisodeQualityGate, write_quality_report

    metadata = manifest.get("metadata")
    metadata = metadata if isinstance(metadata, Mapping) else {}
    capture_config = metadata.get("capture_config")
    capture_config = capture_config if isinstance(capture_config, Mapping) else {}
    alignment = capture_config.get("alignment")
    alignment = alignment if isinstance(alignment, Mapping) else {}
    quality_thresholds = metadata.get(
        "quality_thresholds",
        metadata.get("quality", capture_config.get("quality")),
    )
    quality_thresholds = (
        dict(quality_thresholds) if isinstance(quality_thresholds, Mapping) else None
    )
    gate = EpisodeQualityGate(
        require_complete_capture=manifest.get("source_scope") == "camera_capture",
        thresholds=quality_thresholds,
        max_camera_clock_mapping_uncertainty_sec=alignment.get(
            "max_camera_clock_mapping_uncertainty_sec"
        ),
        max_state_age_sec=alignment.get("max_state_age_sec"),
        max_camera_age_sec=alignment.get("max_camera_age_sec"),
        max_timer_deadline_misses=(
            quality_thresholds.get("max_timer_deadline_misses", 0)
            if isinstance(quality_thresholds, Mapping)
            else 0
        ),
    )
    try:
        report = gate.evaluate(path / "manifest.json")
    except Exception as exc:  # pragma: no cover - defensive recovery path
        report = {
            "report_schema": "robo_collector.episode_quality.v1",
            "episode_id": manifest.get("episode_id"),
            "status": "REVIEW",
            "statistics": {},
            "reason": [f"quality_report_generation_failed: {exc}"],
        }
    report["recovery"] = {
        "generated_at_startup": True,
        "generated_at": time.time(),
    }
    write_quality_report(path, report)


def _new_stream_stats(stream: str) -> dict[str, Any]:
    return {
        "stream_name": stream,
        "frame_count": 0,
        "first_sequence": None,
        "last_sequence": None,
        "sequence_gap_count": 0,
        "producer_gap_count": 0,
        "publisher_gap_count": 0,
        "transport_gap_count": 0,
        "unattributed_gap_count": 0,
        "selection_gap_count": 0,
        "duplicate_count": 0,
        "reorder_count": 0,
        "serial": None,
        "session_ids": [],
        "session_restart_count": 0,
        "last_session_id": None,
        "clock_domain": None,
        "timestamp_quality": None,
        "timestamp_key": None,
        "last_timestamp": None,
        "timestamp_duplicate_count": 0,
        "timestamp_reorder_count": 0,
        "timestamp_monotonic": True,
    }


def _non_negative_count(value: Any, field: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        raise ValueError(f"{field} must be a non-negative integer")
    return value


def _update_stream_stats(
    stats: dict[str, Any],
    provenance: Mapping[str, Any],
    extra: Mapping[str, Any],
) -> None:
    sequence = _sequence(provenance["sequence"])
    session_id = extra.get("session_id")
    session_id = str(session_id) if session_id else None
    same_session = (
        session_id is None
        or stats.get("last_session_id") in {None, session_id}
    )
    previous = stats["last_sequence"]
    if stats["first_sequence"] is None or not same_session:
        stats["first_sequence"] = sequence
    if previous is not None and same_session:
        if sequence == previous:
            stats["duplicate_count"] += 1
        elif sequence < previous:
            stats["reorder_count"] += 1
        else:
            missing = sequence - previous - 1
            stats["sequence_gap_count"] += missing
            producer_given = "producer_gap_count" in extra
            publisher_given = "publisher_gap_count" in extra
            transport_given = "transport_gap_count" in extra
            unattributed_given = "unattributed_gap_count" in extra
            producer = _non_negative_count(
                extra.get("producer_gap_count", 0), "producer_gap_count"
            )
            publisher = _non_negative_count(
                extra.get("publisher_gap_count", 0), "publisher_gap_count"
            )
            transport = _non_negative_count(
                extra.get("transport_gap_count", 0), "transport_gap_count"
            )
            unattributed = _non_negative_count(
                extra.get("unattributed_gap_count", 0),
                "unattributed_gap_count",
            )
            given = {
                "producer": producer_given,
                "publisher": publisher_given,
                "transport": transport_given,
                "unattributed": unattributed_given,
            }
            if not any(given.values()):
                transport = missing
            else:
                known = producer + publisher + transport + unattributed
                missing_fields = [name for name, present in given.items() if not present]
                if known > missing:
                    raise ValueError(
                        f"gap attribution does not equal sequence gap for {stats['stream_name']}"
                    )
                if len(missing_fields) == 1:
                    remainder = missing - known
                    if missing_fields[0] == "producer":
                        producer = remainder
                    elif missing_fields[0] == "publisher":
                        publisher = remainder
                    elif missing_fields[0] == "transport":
                        transport = remainder
                    else:
                        unattributed = remainder
                elif missing_fields:
                    # A producer-only annotation is the legacy camera
                    # contract: all remaining missing frames were observed as
                    # transport gaps.  New collectors pass all four classes
                    # explicitly, so this fallback cannot hide a known class.
                    transport = missing - producer - publisher - unattributed
                elif known != missing:
                    raise ValueError(
                        f"gap attribution does not equal sequence gap for {stats['stream_name']}"
                    )
            if min(producer, publisher, transport, unattributed) < 0 or (
                producer + publisher + transport + unattributed != missing
            ):
                raise ValueError(
                    f"gap attribution does not equal sequence gap for {stats['stream_name']}"
                )
            stats["producer_gap_count"] += producer
            stats["publisher_gap_count"] += publisher
            stats["transport_gap_count"] += transport
            stats["unattributed_gap_count"] += unattributed
    stats["last_sequence"] = sequence
    timestamp_key, timestamp = _provenance_timestamp(provenance)
    if timestamp is not None:
        previous_key = stats.get("timestamp_key")
        previous_timestamp = stats.get("last_timestamp")
        if previous_timestamp is not None and previous_key == timestamp_key:
            if timestamp == previous_timestamp:
                stats["timestamp_duplicate_count"] += 1
                stats["timestamp_monotonic"] = False
            elif timestamp < previous_timestamp:
                stats["timestamp_reorder_count"] += 1
                stats["timestamp_monotonic"] = False
        stats["timestamp_key"] = timestamp_key
        stats["last_timestamp"] = timestamp
    stats["frame_count"] += 1
    serial = extra.get("serial")
    if serial:
        if stats["serial"] is None:
            stats["serial"] = str(serial)
        elif stats["serial"] != str(serial):
            stats["serial"] = "mixed"
    if session_id:
        if session_id not in stats["session_ids"]:
            if stats["session_ids"]:
                stats["session_restart_count"] += 1
            stats["session_ids"].append(session_id)
        stats["last_session_id"] = session_id
    if stats["clock_domain"] is None:
        stats["clock_domain"] = str(provenance["clock_domain"])
    elif stats["clock_domain"] != provenance["clock_domain"]:
        stats["clock_domain"] = "mixed"
    quality = provenance.get("timestamp_quality")
    if quality is not None:
        if stats["timestamp_quality"] is None:
            stats["timestamp_quality"] = str(quality)
        elif stats["timestamp_quality"] != quality:
            stats["timestamp_quality"] = "mixed"
    stats["selection_gap_count"] += _non_negative_count(
        extra.get("selection_gap_count", 0), "selection_gap_count"
    )


def _common_record(
    episode_id: str,
    stream: str,
    provenance: Mapping[str, Any],
) -> dict[str, Any]:
    _safe_component(stream, "stream_name")
    overridden = {"episode_id", "stream_name"}.intersection(provenance)
    if overridden:
        raise ValueError(
            "provenance cannot override raw record fields: "
            + ",".join(sorted(overridden))
        )
    missing = sorted({"session_id", "sequence", "clock_domain"}.difference(provenance))
    if missing:
        raise ValueError("provenance missing: " + ",".join(missing))
    clock_domain = provenance["clock_domain"]
    if not isinstance(clock_domain, str) or not clock_domain.strip():
        raise ValueError("clock_domain must be a non-empty string")
    session_id = provenance["session_id"]
    if not isinstance(session_id, str) or not session_id.strip():
        raise ValueError("session_id must be a non-empty string")
    _sequence(provenance["sequence"])
    timestamp_keys = (
        "device_timestamp",
        "server_wall_timestamp",
        "server_monotonic_timestamp",
        "receive_wall_timestamp",
        "receive_monotonic_timestamp",
        "record_monotonic_timestamp",
    )
    if not any(key in provenance and provenance[key] is not None for key in timestamp_keys):
        raise ValueError("provenance requires at least one timestamp")
    for key in timestamp_keys:
        if key in provenance and provenance[key] is not None:
            _finite_number(provenance[key], key)
    return {"episode_id": episode_id, "stream_name": stream, **dict(provenance)}


def _validate_extra_fields(extra: Mapping[str, Any]) -> None:
    overridden = _RESERVED_EXTRA_FIELDS.intersection(extra)
    if overridden:
        raise ValueError(
            "extra cannot override raw record fields: "
            + ",".join(sorted(overridden))
        )


def _provenance_timestamp(provenance: Mapping[str, Any]) -> tuple[str | None, float | None]:
    for key in (
        "receive_monotonic_timestamp",
        "record_monotonic_timestamp",
        "receive_wall_timestamp",
        "server_monotonic_timestamp",
        "server_wall_timestamp",
        "device_timestamp",
    ):
        if key in provenance and provenance[key] is not None:
            value = _finite_number(provenance[key], key)
            unit = provenance.get("device_unit") if key == "device_timestamp" else None
            if unit == "ms": value *= 1e-3
            elif unit == "us": value *= 1e-6
            elif unit == "ns": value *= 1e-9
            return key, value
    return None, None


def _validate_record_semantics(record: Mapping[str, Any]) -> None:
    required = ("episode_id", "stream_name", "session_id", "sequence", "clock_domain")
    missing = [key for key in required if key not in record]
    if missing:
        raise CorruptChunk("record missing required fields: " + ",".join(missing))
    if not isinstance(record["episode_id"], str):
        raise CorruptChunk("record episode_id must be a string")
    _safe_episode_id(record["episode_id"])
    _safe_component(record["stream_name"], "stream_name")
    if (
        not isinstance(record["session_id"], str)
        or not record["session_id"].strip()
        or not _SESSION_ID.fullmatch(record["session_id"])
    ):
        raise CorruptChunk("record session_id must be a non-empty string")
    _sequence(record["sequence"])
    if not isinstance(record["clock_domain"], str) or not record["clock_domain"].strip():
        raise CorruptChunk("record clock_domain must be a non-empty string")
    timestamp_keys = (
        "device_timestamp",
        "server_wall_timestamp",
        "server_monotonic_timestamp",
        "receive_wall_timestamp",
        "receive_monotonic_timestamp",
        "record_monotonic_timestamp",
    )
    if not any(record.get(key) is not None for key in timestamp_keys):
        raise CorruptChunk("record requires at least one timestamp")
    for key in timestamp_keys:
        if record.get(key) is not None:
            _finite_number(record[key], key)


class RawEpisodeRecorder:
    """Append raw camera/state/event records to bounded durable chunks."""

    def __init__(
        self,
        root: str | os.PathLike[str],
        episode_id: str,
        source_scope: str = "transport_observed",
        *,
        metadata: Mapping[str, Any] | None = None,
        task_prompt: str = "",
        collector_git_commit: str = "",
        config_hash: str = "",
        max_record_bytes: int = _DEFAULT_MAX_RECORD_BYTES,
        max_records_per_chunk: int = _DEFAULT_MAX_RECORDS_PER_CHUNK,
    ) -> None:
        _safe_episode_id(episode_id)
        if source_scope not in SOURCE_SCOPES:
            raise ValueError(f"invalid source_scope: {source_scope}")
        if max_record_bytes <= 0 or max_records_per_chunk <= 0:
            raise ValueError("chunk limits must be positive")

        self.root = Path(root).resolve()
        self.path = self.root / episode_id
        if self.path.exists():
            raise FileExistsError(self.path)
        self.root.mkdir(parents=True, exist_ok=True)
        self.path.mkdir()
        self.max_record_bytes = int(max_record_bytes)
        self.max_records_per_chunk = int(max_records_per_chunk)
        self._files: dict[str, _ChunkHandle] = {}
        self._record_counts: dict[str, int] = {}
        self._stream_stats: dict[str, dict[str, Any]] = {}
        self._record_errors: dict[str, Any] = {
            "total": 0,
            "by_stream": {},
            "by_error_type": {},
        }
        self._lock = threading.RLock()
        self._closed = False
        self._manifest = {
            "schema": SCHEMA,
            "episode_id": episode_id,
            "status": "OPEN",
            "source_scope": source_scope,
            "capture_plane": (
                "host_receiver"
                if source_scope == "transport_observed"
                else "camera_capture"
            ),
            "task_prompt": task_prompt,
            "collector_git_commit": collector_git_commit,
            "config_hash": config_hash,
            "start_wall_time": time.time(),
            "end_wall_time": None,
            "streams": {},
            "record_counts": {},
            "record_errors": self._record_errors,
            "materialization_jobs": [],
            "artifacts": {},
            "quality": {},
            "metadata": dict(metadata or {}),
            "termination": None,
        }
        _atomic_json(self.path / "manifest.inprogress.json", self._manifest)
        _sync_dir(self.path)

    @property
    def closed(self) -> bool:
        return self._closed

    @property
    def manifest(self) -> dict[str, Any]:
        return _read_manifest(self.path)

    def update_status(self, status: str, **fields: Any) -> dict[str, Any]:
        """Atomically update the persistent lifecycle status."""
        with self._lock:
            return self._update_status(status, **fields)

    def update_metadata(self, values: Mapping[str, Any]) -> dict[str, Any]:
        """Merge JSON-safe capture metadata into the open manifest."""
        if not isinstance(values, Mapping):
            raise TypeError("metadata must be a mapping")
        with self._lock:
            if self._closed:
                raise RawEpisodeError("closed episode metadata cannot be updated")
            manifest = _read_manifest(self.path)
            current = manifest.get("metadata", {})
            metadata = dict(current) if isinstance(current, Mapping) else {}
            metadata.update(_canonical_value(dict(values)))
            manifest["metadata"] = metadata
            manifest["streams"] = self._stream_stats
            manifest["record_counts"] = self._record_counts
            manifest["record_errors"] = self._record_errors
            _atomic_json(self.path / "manifest.inprogress.json", manifest)
            self._manifest = manifest
            return dict(metadata)

    def _update_status(self, status: str, **fields: Any) -> dict[str, Any]:
        if status not in STATUSES:
            raise ValueError(f"invalid status: {status}")
        manifest = _read_manifest(self.path)
        current = manifest.get("status")
        if current != status and status not in _ALLOWED_TRANSITIONS.get(current, set()):
            raise RawEpisodeError(f"invalid lifecycle transition: {current} -> {status}")
        if self._closed and status == "OPEN":
            raise RawEpisodeError("closed episode cannot become OPEN")
        manifest.update(fields)
        manifest["status"] = status
        if not self._closed:
            manifest["streams"] = self._stream_stats
            manifest["record_counts"] = self._record_counts
            manifest["record_errors"] = self._record_errors
        target = self.path / (
            "manifest.json" if self._closed else "manifest.inprogress.json"
        )
        _atomic_json(target, manifest)
        self._manifest = manifest
        return dict(manifest)

    def append_camera(
        self,
        stream: str,
        payload: bytes | bytearray | memoryview,
        provenance: Mapping[str, Any],
        *,
        payload_encoding: str = "application/octet-stream",
        **extra: Any,
    ) -> None:
        with self._lock:
            try:
                self._append_camera(
                    stream,
                    payload,
                    provenance,
                    payload_encoding=payload_encoding,
                    **extra,
                )
            except Exception as exc:
                self._record_rejection_locked(stream, type(exc).__name__)
                raise

    def _append_camera(
        self,
        stream: str,
        payload: bytes | bytearray | memoryview,
        provenance: Mapping[str, Any],
        *,
        payload_encoding: str = "application/octet-stream",
        **extra: Any,
    ) -> None:
        if not isinstance(payload, (bytes, bytearray, memoryview)):
            raise TypeError("camera payload must be bytes-like")
        if not isinstance(payload_encoding, str) or not payload_encoding:
            raise ValueError("payload_encoding must be a non-empty string")
        _validate_extra_fields(extra)
        session_id = provenance.get("session_id", extra.get("session_id"))
        if not isinstance(session_id, str) or not session_id.strip():
            raise ValueError("camera provenance requires a non-empty session_id")
        record = _common_record(self._episode_id(), stream, provenance)
        record.update(extra)
        record["session_id"] = session_id
        record.update(
            {
                "payload": base64.b64encode(bytes(payload)).decode("ascii"),
                "payload_encoding": payload_encoding,
                "payload_size_bytes": len(payload),
            }
        )
        stats = copy.deepcopy(
            self._stream_stats.get(stream, _new_stream_stats(stream))
        )
        _update_stream_stats(stats, provenance, {**extra, "session_id": session_id})
        self._append("camera", stream, record)
        self._stream_stats[stream] = stats

    def append_robot_state(
        self,
        state: Mapping[str, Any],
        provenance: Mapping[str, Any],
        stream: str = "state",
        **extra: Any,
    ) -> None:
        with self._lock:
            try:
                self._append_robot_state(state, provenance, stream, **extra)
            except Exception as exc:
                self._record_rejection_locked(stream, type(exc).__name__)
                raise

    def _append_robot_state(
        self,
        state: Mapping[str, Any],
        provenance: Mapping[str, Any],
        stream: str = "state",
        **extra: Any,
    ) -> None:
        if not isinstance(state, Mapping):
            raise TypeError("robot state must be a mapping")
        _validate_extra_fields(extra)
        record = _common_record(self._episode_id(), stream, provenance)
        record.update(extra)
        record["state"] = dict(state)
        stats = copy.deepcopy(self._stream_stats.get(stream, _new_stream_stats(stream)))
        _update_stream_stats(stats, provenance, {**extra, "session_id": provenance["session_id"]})
        self._append("robot", "state", record)
        self._stream_stats[stream] = stats

    def append_event(
        self,
        event: Mapping[str, Any],
        provenance: Mapping[str, Any],
        stream: str = "events",
    ) -> None:
        with self._lock:
            try:
                self._append_event(event, provenance, stream)
            except Exception as exc:
                self._record_rejection_locked(stream, type(exc).__name__)
                raise

    def _append_event(
        self,
        event: Mapping[str, Any],
        provenance: Mapping[str, Any],
        stream: str = "events",
    ) -> None:
        if not isinstance(event, Mapping):
            raise TypeError("event must be a mapping")
        record = _common_record(self._episode_id(), stream, provenance)
        record["event"] = dict(event)
        stats = copy.deepcopy(self._stream_stats.get(stream, _new_stream_stats(stream)))
        _update_stream_stats(stats, provenance, {"session_id": provenance["session_id"]})
        self._append("events", "events", record)
        self._stream_stats[stream] = stats

    def record_rejection(
        self, stream: str, error_type: str, count: int = 1
    ) -> None:
        """Persist a bounded count for an input rejected before append."""
        with self._lock:
            self._record_rejection_locked(stream, error_type, count=count)

    def _record_rejection_locked(
        self, stream: str, error_type: str, *, count: int = 1
    ) -> None:
        if self._closed:
            return
        _safe_component(stream, "stream_name")
        amount = _non_negative_count(count, "rejection_count")
        if amount <= 0:
            raise ValueError("rejection_count must be positive")
        error_key = str(error_type).strip() or "unknown"
        errors = copy.deepcopy(self._record_errors)
        errors["total"] = int(errors.get("total", 0) or 0) + amount
        by_stream = errors.setdefault("by_stream", {})
        by_type = errors.setdefault("by_error_type", {})
        by_stream[str(stream)] = (
            int(by_stream.get(str(stream), 0) or 0) + amount
        )
        by_type[error_key] = int(by_type.get(error_key, 0) or 0) + amount
        self._record_errors = errors
        manifest = _read_manifest(self.path)
        manifest["record_errors"] = errors
        manifest["streams"] = self._stream_stats
        manifest["record_counts"] = self._record_counts
        _atomic_json(self.path / "manifest.inprogress.json", manifest)
        self._manifest = manifest

    def close(self, *, command: str = "STOP", reason: str = "user_stop") -> dict[str, Any]:
        """Seal chunks and atomically publish a ``RAW_CLOSED`` manifest."""
        with self._lock:
            if self._closed:
                return self.manifest
            return self._seal("RAW_CLOSED", command=command, reason=reason)

    def discard(self, *, reason: str = "user_discard") -> dict[str, Any]:
        """Seal and retain raw records while marking the episode discarded."""
        with self._lock:
            if self._closed:
                return self._update_status(
                    "DISCARDED",
                    termination={"command": "DISCARD", "reason": reason},
                )
            return self._seal("DISCARDED", command="DISCARD", reason=reason)

    def quarantine(self, reason: str) -> dict[str, Any]:
        with self._lock:
            if self._closed:
                return self._update_status(
                    "QUARANTINED", quarantine_error=str(reason)
                )
            return self._seal("QUARANTINED", command="QUARANTINE", reason=str(reason))

    def _episode_id(self) -> str:
        return str(self._manifest["episode_id"])

    def _append(self, category: str, name: str, record: Mapping[str, Any]) -> None:
        if self._closed:
            raise RawEpisodeError("episode is closed")
        _safe_component(category, "category")
        _safe_component(name, "stream_name")
        _validate_record_semantics(record)
        encoded = _json_bytes(record)
        if len(encoded) > self.max_record_bytes:
            raise ValueError("record exceeds max_record_bytes")

        key = f"{category}/{name}"
        chunk = self._files.get(key)
        if chunk is None or chunk.record_count >= self.max_records_per_chunk:
            if chunk is not None:
                _sync_file(chunk.handle)
                chunk.handle.close()
            directory = self.path / category / name
            directory.mkdir(parents=True, exist_ok=True)
            index = self._record_counts.get(key, 0) // self.max_records_per_chunk
            handle = (directory / f"chunk-{index:06d}.raw").open("ab")
            chunk = _ChunkHandle(handle=handle, index=index, record_count=0)
            self._files[key] = chunk

        checksum = binascii.crc32(encoded) & 0xFFFFFFFF
        chunk.handle.write(_HEADER.pack(_MAGIC, len(encoded), checksum))
        chunk.handle.write(encoded)
        chunk.handle.flush()
        chunk.record_count += 1
        self._record_counts[key] = self._record_counts.get(key, 0) + 1

    def _close_files(self, *, sync: bool) -> None:
        for chunk in list(self._files.values()):
            try:
                if sync:
                    _sync_file(chunk.handle)
                else:
                    chunk.handle.flush()
            finally:
                chunk.handle.close()
        self._files.clear()

    def _seal(self, status: str, *, command: str, reason: str) -> dict[str, Any]:
        self._close_files(sync=True)
        manifest = _read_manifest(self.path)
        manifest["streams"] = self._stream_stats
        manifest["record_counts"] = self._record_counts
        manifest["record_errors"] = self._record_errors
        checksums = _checksums(self.path)
        manifest["checksums"] = checksums
        _write_checksums(self.path, checksums)
        manifest["status"] = status
        manifest["end_wall_time"] = time.time()
        manifest["termination"] = {"command": command, "reason": reason}
        raw_hash = _hash_manifest(manifest)
        manifest["manifest_hash"] = raw_hash
        manifest["raw_manifest_hash"] = raw_hash
        _publish_manifest(self.path, manifest)
        self._manifest = manifest
        self._closed = True
        return dict(manifest)

    def __del__(self) -> None:  # pragma: no cover - best-effort interpreter cleanup
        try:
            self._close_files(sync=False)
        except Exception:
            pass


_ALLOWED_TRANSITIONS: dict[str, set[str]] = {
    "OPEN": {"RAW_CLOSED", "DISCARDED", "QUARANTINED"},
    "RAW_CLOSED": {"MATERIALIZING", "DISCARDED", "QUARANTINED"},
    "MATERIALIZING": {"MATERIALIZED", "MATERIALIZATION_FAILED", "QUARANTINED"},
    "MATERIALIZATION_FAILED": {"MATERIALIZING", "DISCARDED", "QUARANTINED"},
    "MATERIALIZED": {"MATERIALIZING", "QC", "QUARANTINED"},
    "QC": {"READY", "REVIEW", "REJECT", "QUARANTINED"},
    "READY": {"READY", "REVIEW", "REJECT"},
    "REVIEW": {"REVIEW", "READY", "REJECT"},
    "REJECT": {"REJECT", "REVIEW", "READY"},
    "DISCARDED": {"DISCARDED"},
    "QUARANTINED": {"QUARANTINED"},
}


class RawEpisodeReader:
    """Read and validate a sealed raw episode."""

    def __init__(self, path: str | os.PathLike[str]):
        self.path = Path(path).resolve()
        self.manifest = _read_manifest(self.path)
        if self.manifest.get("schema") != SCHEMA:
            raise RawEpisodeError("unsupported raw episode schema")
        if not (self.path / "manifest.json").exists():
            raise RawEpisodeError("raw episode is not sealed")

    @staticmethod
    def read_chunk(
        path: Path,
        *,
        max_record_bytes: int = _DEFAULT_MAX_RECORD_BYTES,
    ) -> Iterator[dict[str, Any]]:
        with path.open("rb") as stream:
            while True:
                header = stream.read(_HEADER.size)
                if not header:
                    return
                if len(header) != _HEADER.size:
                    raise CorruptChunk(f"truncated header: {path}")
                magic, size, checksum = _HEADER.unpack(header)
                if magic != _MAGIC or size > max_record_bytes:
                    raise CorruptChunk(f"invalid record header: {path}")
                data = stream.read(size)
                if len(data) != size:
                    raise CorruptChunk(f"truncated record: {path}")
                if binascii.crc32(data) & 0xFFFFFFFF != checksum:
                    raise CorruptChunk(f"checksum mismatch: {path}")
                try:
                    value = json.loads(data.decode("utf-8"))
                except (UnicodeDecodeError, json.JSONDecodeError) as exc:
                    raise CorruptChunk(f"invalid JSON record: {path}") from exc
                if not isinstance(value, dict):
                    raise CorruptChunk(f"record is not an object: {path}")
                _validate_record_semantics(value)
                yield value

    def records(self, category: str, name: str) -> Iterator[dict[str, Any]]:
        _safe_component(category, "category")
        _safe_component(name, "stream_name")
        directory = self.path / category / name
        for chunk in sorted(directory.glob("*.raw")):
            yield from self.read_chunk(chunk)

    def validate(self) -> None:
        raw_manifest_hash = self.manifest.get("raw_manifest_hash")
        if raw_manifest_hash and _hash_manifest(self.manifest) != raw_manifest_hash:
            raise CorruptChunk("raw manifest hash mismatch")
        manifest_checksums = self.manifest.get("checksums")
        if not isinstance(manifest_checksums, Mapping):
            raise CorruptChunk("manifest checksums are missing")
        checksums = _read_checksums(self.path)
        if not checksums:
            # Accept pre-checksums.json episodes produced by the first v1
            # implementation, while all newly sealed episodes publish both
            # representations.
            checksums = {
                str(name): str(checksum)
                for name, checksum in manifest_checksums.items()
            }
        elif dict(manifest_checksums) != checksums:
            raise CorruptChunk("manifest and checksums.json disagree")
        actual_files = _raw_files(self.path)
        actual_names = {str(file.relative_to(self.path)) for file in actual_files}
        expected_names = {str(name) for name in checksums}
        if actual_names != expected_names:
            raise CorruptChunk("manifest raw file list does not match disk")
        for relative, expected in checksums.items():
            file = self.path / str(relative)
            if _sha256(file) != expected:
                raise CorruptChunk(f"checksum mismatch: {relative}")
            parts = file.relative_to(self.path).parts
            category, name = parts[0], parts[1]
            for record in self.read_chunk(file):
                if record.get("episode_id") != self.manifest.get("episode_id"):
                    raise CorruptChunk(f"record episode_id mismatch: {relative}")
                if record.get("stream_name") != name:
                    raise CorruptChunk(f"record stream_name mismatch: {relative}")
                if category == "camera":
                    payload = record.get("payload")
                    encoding = record.get("payload_encoding")
                    if not isinstance(payload, str) or not isinstance(encoding, str) or not encoding:
                        raise CorruptChunk(f"camera record payload missing: {relative}")
                    try:
                        decoded = base64.b64decode(payload.encode("ascii"), validate=True)
                    except (UnicodeEncodeError, ValueError, binascii.Error) as exc:
                        raise CorruptChunk(f"camera record payload is not base64: {relative}") from exc
                    declared_size = record.get("payload_size_bytes")
                    if declared_size is not None and (
                        not isinstance(declared_size, int)
                        or isinstance(declared_size, bool)
                        or declared_size != len(decoded)
                    ):
                        raise CorruptChunk(f"camera record payload size mismatch: {relative}")
                if category == "robot" and not isinstance(record.get("state"), Mapping):
                    raise CorruptChunk(f"robot record state missing: {relative}")
                if category == "events" and not isinstance(record.get("event"), Mapping):
                    raise CorruptChunk(f"event record payload missing: {relative}")

        actual_streams, actual_record_counts = _scan_records(self.path)
        manifest_streams = self.manifest.get("streams")
        manifest_record_counts = self.manifest.get("record_counts")
        if not isinstance(manifest_streams, Mapping) or not isinstance(
            manifest_record_counts, Mapping
        ):
            raise CorruptChunk("manifest stream statistics are missing")
        if dict(manifest_record_counts) != actual_record_counts:
            raise CorruptChunk("manifest record counts do not match raw chunks")
        if dict(manifest_streams) != actual_streams:
            raise CorruptChunk("manifest stream statistics do not match raw chunks")


def _scan_records(path: Path) -> tuple[dict[str, dict[str, Any]], dict[str, int]]:
    streams: dict[str, dict[str, Any]] = {}
    record_counts: dict[str, int] = {}
    for chunk in _raw_files(path):
        relative = chunk.relative_to(path).parts
        if len(relative) < 3:
            raise CorruptChunk(f"raw chunk has invalid path: {chunk}")
        category, name = relative[0], relative[1]
        key = f"{category}/{name}"
        count = 0
        for record in RawEpisodeReader.read_chunk(chunk):
            count += 1
            if category == "camera":
                stream = str(record.get("stream_name", name))
                if stream not in streams:
                    streams[stream] = _new_stream_stats(stream)
                _update_stream_stats(streams[stream], record, record)
            elif category == "robot":
                stream = str(record.get("stream_name", "state"))
                streams.setdefault(stream, _new_stream_stats(stream))
                _update_stream_stats(streams[stream], record, record)
            elif category == "events":
                stream = str(record.get("stream_name", "events"))
                streams.setdefault(stream, _new_stream_stats(stream))
                _update_stream_stats(streams[stream], record, record)
        record_counts[key] = record_counts.get(key, 0) + count
    return streams, record_counts


def _repair_chunk_tail(path: Path) -> bool:
    """Truncate only an incomplete final header/record; reject bad prefixes."""
    with path.open("r+b") as stream:
        valid_end = 0
        while True:
            header = stream.read(_HEADER.size)
            if not header:
                break
            if len(header) != _HEADER.size:
                stream.truncate(valid_end)
                _sync_file(stream)
                return True
            magic, size, checksum = _HEADER.unpack(header)
            if magic != _MAGIC or size > _DEFAULT_MAX_RECORD_BYTES:
                raise CorruptChunk(f"invalid record header: {path}")
            data = stream.read(size)
            if len(data) != size:
                stream.truncate(valid_end)
                _sync_file(stream)
                return True
            if binascii.crc32(data) & 0xFFFFFFFF != checksum:
                raise CorruptChunk(f"checksum mismatch: {path}")
            try:
                value = json.loads(data.decode("utf-8"))
            except (UnicodeDecodeError, json.JSONDecodeError) as exc:
                raise CorruptChunk(f"invalid JSON record: {path}") from exc
            if not isinstance(value, dict):
                raise CorruptChunk(f"record is not an object: {path}")
            valid_end = stream.tell()
    return False


def _seal_recovered_episode(
    path: Path, progress_manifest: Mapping[str, Any]
) -> dict[str, Any]:
    for chunk in _raw_files(path):
        _repair_chunk_tail(chunk)
    streams, record_counts = _scan_records(path)
    manifest = dict(progress_manifest)
    metadata = manifest.get("metadata")
    if isinstance(metadata, Mapping):
        metadata = dict(metadata)
        binding = metadata.get("camera_capture_binding")
        if isinstance(binding, Mapping) and binding.get("status") == "OPEN":
            binding = dict(binding)
            binding.update(
                {
                    "status": "RECOVERED_OPEN_NEEDS_REBIND",
                    "recovery_reason": "process_crash_before_source_snapshot",
                    "recovered_wall_time": time.time(),
                }
            )
            metadata["camera_capture_binding"] = binding
            manifest["metadata"] = metadata
    manifest.update(
        {
            "status": "RAW_CLOSED",
            "end_wall_time": time.time(),
            "streams": streams,
            "record_counts": record_counts,
            "checksums": _checksums(path),
            "termination": {"command": "RECOVERY", "reason": "process_crash"},
        }
    )
    _write_checksums(path, manifest["checksums"])
    raw_hash = _hash_manifest(manifest)
    manifest["manifest_hash"] = raw_hash
    manifest["raw_manifest_hash"] = raw_hash
    _publish_manifest(path, manifest)
    return manifest


def _quarantine_path(path: Path, error: BaseException) -> None:
    source = path / "manifest.json"
    if not source.exists():
        source = path / "manifest.inprogress.json"
    try:
        manifest = json.loads(source.read_text(encoding="utf-8"))
    except Exception:
        manifest = {"schema": SCHEMA, "episode_id": path.name}
    manifest.update(status="QUARANTINED", quarantine_error=str(error))
    _atomic_json(path / "manifest.json", manifest)
    try:
        (path / "manifest.inprogress.json").unlink()
    except FileNotFoundError:
        pass
    _sync_dir(path)


def scan_startup(
    root: str | os.PathLike[str],
    *,
    default_materialization_config: Mapping[str, Any] | None = None,
    default_output_schema_version: str = "lerobot.v2.1.raw_materialization.v1",
) -> list[dict[str, Any]]:
    """Recover raw episodes and return retryable materialization jobs.

    A crash can happen after the raw manifest is durably sealed but before the
    materialization job append is durable.  When a closed episode carries the
    capture-time conversion config (or the caller supplies a default), create
    that missing job during startup so the episode is not silently stranded.
    """
    root_path = Path(root).resolve()
    if not root_path.exists():
        return []
    jobs: list[dict[str, Any]] = []
    for path in sorted(item for item in root_path.iterdir() if item.is_dir()):
        progress = path / "manifest.inprogress.json"
        closed = path / "manifest.json"
        try:
            manifest: dict[str, Any]
            reset_running = False
            if closed.exists():
                # The final manifest is authoritative.  Never use progress as
                # a repair source once final exists: a bad final must be
                # quarantined using that final (or the generic fallback).
                manifest = json.loads(closed.read_text(encoding="utf-8"))
                reader = RawEpisodeReader(path)
                reader.validate()
                if progress.exists():
                    progress.unlink()
                    _sync_dir(path)
            elif progress.exists():
                manifest = json.loads(progress.read_text(encoding="utf-8"))
                if manifest.get("status") == "OPEN":
                    manifest = _seal_recovered_episode(path, manifest)
                else:
                    raise RawEpisodeError("in-progress manifest is not OPEN")
            else:
                continue
            reader = RawEpisodeReader(path)
            reader.validate()
            if manifest.get("status") in {"DISCARDED", "QUARANTINED"}:
                continue
            if manifest.get("status") in {
                "RAW_CLOSED",
                "MATERIALIZING",
                "MATERIALIZATION_FAILED",
                "MATERIALIZED",
                "QC",
                "READY",
                "REVIEW",
                "REJECT",
            }:
                _ensure_startup_quality_report(path, manifest)
            existing_jobs = manifest.get("materialization_jobs", [])
            if (
                manifest.get("status") in {
                    "RAW_CLOSED",
                    "MATERIALIZING",
                    "MATERIALIZATION_FAILED",
                    "MATERIALIZED",
                    "QC",
                }
                and isinstance(existing_jobs, list)
                and not existing_jobs
            ):
                metadata = manifest.get("metadata")
                metadata = metadata if isinstance(metadata, Mapping) else {}
                configured = metadata.get("conversion_config")
                if not isinstance(configured, Mapping):
                    configured = default_materialization_config
                schema_version = metadata.get(
                    "output_schema_version", default_output_schema_version
                )
                if isinstance(configured, Mapping) and isinstance(schema_version, str) and schema_version:
                    create_materialization_job(
                        path,
                        configured,
                        schema_version,
                    )
                    manifest = _read_manifest(path)
            for job in manifest.get("materialization_jobs", []):
                if isinstance(job, dict) and job.get("status") == "RUNNING":
                    job["status"] = "PENDING"
                    job["updated_at"] = time.time()
                    job["last_error"] = "recovered after process crash"
                    reset_running = True
                    if manifest.get("status") == "MATERIALIZING":
                        manifest["status"] = "RAW_CLOSED"
                if not isinstance(job, Mapping):
                    continue
                job_status = job.get("status")
                if job_status == "PENDING" and manifest.get("status") == "MATERIALIZING":
                    # PENDING is durable queue state, not active execution.
                    # Repair a torn marker so a restart cannot leave an
                    # episode falsely reporting an in-flight materializer.
                    manifest["status"] = "RAW_CLOSED"
                    reset_running = True
                elif job_status == "FAILED" and manifest.get("status") == "MATERIALIZING":
                    manifest["status"] = "MATERIALIZATION_FAILED"
                    reset_running = True
                if job_status in {"PENDING", "FAILED"}:
                    jobs.append({"episode": str(path), **dict(job)})
                elif (
                    job_status == "MATERIALIZED"
                    and manifest.get("status") in {"MATERIALIZED", "QC"}
                ):
                    # A crash can leave durable artifacts and either the
                    # MATERIALIZED or QC marker behind before the final
                    # publication/QC decision.  Return the job so the
                    # materializer revalidates evidence and completes the
                    # lifecycle instead of stranding the episode forever.
                    jobs.append(
                        {
                            "episode": str(path),
                            "recovery_action": "revalidate_materialized",
                            **dict(job),
                        }
                    )
            if reset_running:
                _atomic_json(path / "manifest.json", manifest)
        except (
            OSError,
            ValueError,
            KeyError,
            TypeError,
            json.JSONDecodeError,
            RawEpisodeError,
        ) as exc:
            _quarantine_path(path, exc)
    return jobs


def create_materialization_job(
    episode: str | os.PathLike[str],
    config: Mapping[str, Any],
    output_schema_version: str,
    *,
    output_target: str | os.PathLike[str] | Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Create or return an idempotent durable materialization job."""
    if not isinstance(config, Mapping):
        raise TypeError("materialization config must be a mapping")
    if not output_schema_version:
        raise ValueError("output_schema_version is required")
    path = Path(episode).resolve()
    manifest = _read_manifest(path)
    if not (path / "manifest.json").exists():
        raise RawEpisodeError("materialization requires a sealed raw episode")
    canonical_config = _canonical_value(dict(config))
    if output_target is None:
        generated_target = {
            key: canonical_config[key]
            for key in ("output_root", "dataset_name")
            if key in canonical_config
        }
        if not generated_target:
            generated_target = {"episode_id": str(manifest.get("episode_id", path.name))}
        canonical_target = generated_target
    else:
        canonical_target = _safe_output_target(output_target)
    if manifest.get("status") not in {
        "RAW_CLOSED",
        "MATERIALIZING",
        "MATERIALIZATION_FAILED",
        "MATERIALIZED",
        "QC",
        "READY",
        "REVIEW",
        "REJECT",
    }:
        raise RawEpisodeError(f"cannot materialize from {manifest.get('status')}")
    source_hash = str(
        manifest.get("raw_manifest_hash")
        or manifest.get("manifest_hash")
        or _hash_manifest(manifest)
    )
    config_hash = hashlib.sha256(_json_bytes(canonical_config)).hexdigest()
    key = f"{source_hash}:{config_hash}:{output_schema_version}"
    for job in manifest.setdefault("materialization_jobs", []):
        if isinstance(job, Mapping) and job.get("idempotency_key") == key:
            return dict(job)
    # A recovered MATERIALIZING marker with no durable job means the process
    # crashed between the marker write and job creation.  Creating a PENDING
    # job must repair that stale execution marker before publishing the job;
    # otherwise startup recovery can report work that is not actually running.
    if manifest.get("status") == "MATERIALIZING":
        manifest["status"] = "RAW_CLOSED"
    job = {
        "job_id": uuid.uuid4().hex,
        "source_manifest_hash": source_hash,
        "conversion_config_hash": config_hash,
        "conversion_config": canonical_config,
        "output_target": canonical_target,
        "output_schema_version": output_schema_version,
        "idempotency_key": key,
        "status": "PENDING",
        "attempt_count": 0,
        "last_error": None,
        "updated_at": time.time(),
    }
    manifest.setdefault("materialization_jobs", []).append(job)
    # PENDING means the job is durable but not executing.  The lifecycle
    # marker changes to MATERIALIZING only at claim time, so a crash between
    # job creation and worker admission cannot falsely report active work.
    _atomic_json(path / "manifest.json", manifest)
    return dict(job)


def discard_sealed_episode(
    episode: str | os.PathLike[str], *, reason: str = "user_discard"
) -> dict[str, Any]:
    """Safely discard a sealed episode without deleting its raw evidence."""
    path = Path(episode).resolve()
    manifest = _read_manifest(path)
    if not (path / "manifest.json").exists():
        raise RawEpisodeError("discard requires a sealed raw episode")
    if manifest.get("status") not in {
        "RAW_CLOSED", "MATERIALIZING", "MATERIALIZATION_FAILED", "MATERIALIZED", "QC",
        "READY", "REVIEW", "REJECT", "DISCARDED",
    }:
        raise RawEpisodeError(f"cannot discard from {manifest.get('status')}")
    manifest["status"] = "DISCARDED"
    manifest["discarded_at"] = time.time()
    manifest["discard_reason"] = str(reason)
    for job in manifest.get("materialization_jobs", []):
        if isinstance(job, dict) and job.get("status") in {"PENDING", "RUNNING"}:
            job["status"] = "DISCARDED"
            job["last_error"] = f"episode discarded: {reason}"
            job["updated_at"] = time.time()
    # A sealed raw hash covers the capture termination record. Discard is a
    # mutable lifecycle decision, so do not rewrite capture metadata and
    # invalidate the source hash.
    if not manifest.get("raw_manifest_hash"):
        manifest["termination"] = {"command": "DISCARD", "reason": str(reason)}
    _atomic_json(path / "manifest.json", manifest)
    return dict(manifest)


def update_materialization_job(
    episode: str | os.PathLike[str],
    job_id: str,
    status: str,
    *,
    error: str | None = None,
    artifacts: Mapping[str, Any] | None = None,
    increment_attempt: bool = False,
) -> dict[str, Any]:
    if status not in JOB_STATUSES:
        raise ValueError(f"invalid materialization job status: {status}")
    path = Path(episode).resolve()
    manifest = _read_manifest(path)
    jobs = manifest.get("materialization_jobs")
    if not isinstance(jobs, list):
        raise RawEpisodeError("manifest materialization_jobs must be a list")
    for job in jobs:
        if not isinstance(job, dict) or job.get("job_id") != job_id:
            continue
        job["status"] = status
        job["updated_at"] = time.time()
        job["last_error"] = error
        if increment_attempt:
            job["attempt_count"] = int(job.get("attempt_count", 0)) + 1
        if artifacts is not None:
            job["artifacts"] = dict(artifacts)
        if status == "RUNNING":
            manifest["status"] = "MATERIALIZING"
        elif status == "MATERIALIZED":
            manifest["status"] = "MATERIALIZED"
            if artifacts is not None:
                manifest["artifacts"] = dict(artifacts)
        elif status == "FAILED":
            manifest["status"] = "MATERIALIZATION_FAILED"
        elif status == "DISCARDED":
            manifest["status"] = "DISCARDED"
        _atomic_json(path / "manifest.json", manifest)
        return dict(job)
    raise RawEpisodeError(f"materialization job not found: {job_id}")


def reset_materialization_job_for_retry(
    episode: str | os.PathLike[str],
    job_id: str,
    *,
    error: str = "materialized artifacts require revalidation",
) -> dict[str, Any]:
    """Return a stranded materialization job to the durable raw queue.

    This is used only after a prior MATERIALIZED publication fails evidence
    validation.  Raw chunks and capture metadata remain untouched; derived
    artifact pointers are cleared so a later QC pass cannot accidentally trust
    stale output.
    """
    path = Path(episode).resolve()
    manifest = _read_manifest(path)
    jobs = manifest.get("materialization_jobs")
    if not isinstance(jobs, list):
        raise RawEpisodeError("manifest materialization_jobs must be a list")
    for job in jobs:
        if not isinstance(job, dict) or job.get("job_id") != job_id:
            continue
        if job.get("status") not in {"MATERIALIZED", "FAILED", "RUNNING", "PENDING"}:
            raise RawEpisodeError(
                f"cannot reset materialization job from {job.get('status')}"
            )
        job["status"] = "PENDING"
        job["updated_at"] = time.time()
        job["last_error"] = str(error)
        job.pop("artifacts", None)
        manifest["status"] = "RAW_CLOSED"
        manifest.pop("artifacts", None)
        _atomic_json(path / "manifest.json", manifest)
        return dict(job)
    raise RawEpisodeError(f"materialization job not found: {job_id}")


def claim_materialization_job(
    episode: str | os.PathLike[str],
    job_id: str,
) -> dict[str, Any]:
    return update_materialization_job(
        episode,
        job_id,
        "RUNNING",
        increment_attempt=True,
    )


__all__ = [
    "SCHEMA",
    "SOURCE_SCOPES",
    "STATUSES",
    "JOB_STATUSES",
    "RawEpisodeRecorder",
    "RawEpisodeReader",
    "RawEpisodeError",
    "CorruptChunk",
    "claim_materialization_job",
    "create_materialization_job",
    "discard_sealed_episode",
    "reset_materialization_job_for_retry",
    "scan_startup",
    "update_materialization_job",
]
